[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Hitchhiker's Guide to Frequent Problems"
authors = [{name = "JMC", email = "johannamchristoph@proton.me"}]
dynamic = ["version", "description"]
